version: '3'
services:
    app:
        build: .
        restart: always
        ports:
            - '5000:5000'
        links:
            - db    

    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=new
            - MYSQL_USER=newuser
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - "3306"
        